# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07469f217fdf8fa59616a25b13d4d7717c9b78ebed48b1b791174aba0331564c3b507aa47a810e4bb510d5744110109d7102f50ec10bca6305acd7d98ebb52bc

test:
  secret_key_base: bac5b43ddc92afd91479e6f2e2127ac38e740d3da72ea79e91b7e1e4ce201abd0c5188dccfc0d08ea3b825131a4889c70e9843d66023bd62d4fcc4b58737feff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
